<?php

namespace app\admin\controller;

use think\Controller;

class Base extends Controller
{
    //
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        if (!session("id")){
            $this->redirect(url("Login/index"));
        }
        if (!session("role_id")){
            $this->redirect(url("Login/index"));
        }
    }
}
